preprocessor:
  _target_: pipeline.preprocessors.BaseDataPreprocessor

image_generator:
  generator_inference:
    _target_: pipeline.diffusion_pipeline.InpaintControlNetInference
    base_model: runwayml/stable-diffusion-inpainting
  control_methods:
    - depth
    - hed
  generation_config:
    image_size: 768
    num_inference_steps: 50
    guidance_scale:
      - 6.0
      - 7.0
      - 7.5
    condition_scale:
      - 0.7
      - 0.2

postprocessor:
  _target_: pipeline.postprocessors.BasePostprocessor

dataset_config:
  _target_: pipeline.readers.CustomDatasetReader
  data_path: data/VOC2012/JPEGImages
  dataset_config:
    save_folder: data/VOC_augmented
  json_path: data/VOC_annotations/annotations.json

saver:
  _target_: pipeline.converters.MetadataSaver
  save_folder: data/VOC_augmented
